version: 2.1

jobs:
  debug:
    macos:
      xcode: 15.4.0
    steps:
      - checkout
      - run:
          name: Debug
          command: |
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain none
            sleep 1800

workflows:
  debug:
    jobs:
      - debug
